dataset: wl-classify
model:
  # num_layers: 4
  num_layers: 6
  mini_layers: 2
  embs: (0, 1, 2)
  embs_combine_mode: 'concat'
  pool: add
  # hidden_size: 16
  hidden_size: 64
subgraph:
  # hops: 2
  hops: 6
  online: True